# ENVIRONMENT
QE: 10.4
KE: 10.0
BE: 0.5

# OPERATOR
PO: 7
DO: 1.3
FREQ: 1
AMP: 2

# SLAVE
ARM_S: 0.1
JS: 0.0629
BS: 0.0517
BhS: 0.02 #???
JhS: 0.02 #???
KT2CS: 1.182
KC2VS: 2.0
PS: 3
DS: 1.5

# MASTER
ARM_M: 0.1
JM: 0.0629
BM: 0.0517 
BhM: 0.02 #???
JhM: 0.02 #???
KT2CM: 1.182
KC2VM: 2.0
PM: 1
DM: 1

# SIMULATION
TS: 0.005
STEP_SIZE: 0.001
TF_CONTINUOUS: 2
TF_DISCRETE: 10000

# PLOTS
Y_MIN: -2
Y_MAX: 2

DEBUG: False
LOG_FILE: "log.txt"

# TWO LAYER
HMAX: 1.0
HMIN: 0.0
HD: 0.5
ALPHA: 0.1
BETA: 0.1
H0: 0.6

# LORENTZ
LOR_SIGMA: 10.0
LOR_BETA: 2.6667
LOR_RHO: 28.0

# FIXED PACKET LOSS
START_LOSS: 2.3
STOP_LOSS: 2.5

# COMM. CHANNEL PARAMS
LOWER: 0.9623
UPPER: 47.8801
WIDTH: 46.9177
P: 0.62