# ENVIRONMENT
QE: 10
KE: 10.0
BE: 0.5

# OPERATOR
PO: 3
DO: 1.3
START_TIME: 2.0
UP_TIME: 2.002
AMP: 1

# SLAVE
ARM_S: 0.1
JS: 0.0629
BS: 0.0517
BhS: 0.02 #???
JhS: 0.02 #???
KT2CS: 1.182
KC2VS: 2.0
PS: 80
DS: 8.5

# MASTER
ARM_M: 0.1
JM: 0.0629
BM: 0.0517 
BhM: 0.02 #???
JhM: 0.02 #???
KT2CM: 1.182
KC2VM: 2.0
PM: 60
DM: 3

# SIMULATION
TS: 0.005
STEP_SIZE: 0.001
TF_CONTINUOUS: 5
TF_DISCRETE: 100000

# PLOTS
Y_MIN: -2
Y_MAX: 2

DEBUG: False
LOG_FILE: "log.txt"

# TWO LAYER
HMAX: 1.0
HMIN: 0.0
HD: 0.5
ALPHA: 0.1
BETA: 0.1
H0: 0.6